services:
  wotlwedu-frontend:
    environment:
      - WOTLWEDU_SSL_KEY_FILE=/secrets/wotlwedu-frontend/server.key
      - WOTLWEDU_SSL_CERT_FILE=/secrets/wotlwedu-frontend/server.crt
      - WOTLWEDU_API_URL=https://api.wotlwedu.com:9876/
      - WOTLWEDU_SERVER_NAME=www.wotlwedu.com
    image: ravelox/wotlwedu-frontend
    ports:
      - 443:443
    volumes:
        - /secrets/wotlwedu-frontend:/secrets